run:
  default_batch_size: 1000
  max_concurrent_studies: 2
  gene_filter_path: ./config/gene_filter.txt
  input_root: ./studies
  artifacts_db: ./artifacts/artifacts.db
  sql_variant: sqlite
  sqlite_url: sqlite:///artifacts/artifacts.db
  mssql_dsn: DRIVER={ODBC Driver 18 for SQL Server};SERVER=localhost;DATABASE=omics;UID=etl;PWD=secret
logging:
  level: info
  json: true
  log_file: ./logs/etl.log
retry:
  attempts: 5
  backoff_seconds: 2
  backoff_max_seconds: 60
metrics:
  enable: true
  export_path: ./artifacts/metrics.json
